package com.mobileisaccframework.Manager;

// EFFECT ID
public enum EFFECT_ENUM {
    FX_PLAYER_HIT, FX_PLAYER_DIE, FX_BOMB, FX_BOSS_DIE, FX_BULLET_DIE, FX_BULLET_SHOOT, FX_ENEMY_DIE,
    FX_DOOR_OPEN, FX_BLOCK_DIE, FX_CLICK, FX_BOSS_LAND }
